REGISTER QUERY CountEachRoom AS
PREFIX ex: <http://example.org/>
PREFIX onto: <file:///Users/vitor/git-repository/KAFKA/scep-operator/examples/>
SELECT ?o ?pro (count(?p) as ?countPatients)
FROM STREAM <http://example.org> [RANGE TRIPLES 8]
FROM <file:///Users/vitor/git-repository/KAFKA/scep-operator/examples/consultation.rdf>
WHERE
{    
    ?p ex:wasIn ?o       
    BIND (ex:visited AS ?pro)
}
GROUP BY ?o ?pro