REGISTER QUERY EstimateProfit AS
PREFIX ex: <http://example.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT ?hospital ?pro (sum(xsd:integer((?value))) as ?profit)
FROM STREAM <http://example.org> [RANGE TRIPLES 8]
FROM <file:///Users/vitor/git-repository/KAFKA/scep-operator/examples/consultation.rdf>
WHERE
{
    ?patient ex:wasIn ?roomType .
    ?roomType ex:cost ?value . 
    ?room ex:isAllocatedAs ?roomType .
    ?room ex:isRoomOf ?hospital
    BIND (ex:hasProfit AS ?pro)
}
GROUP BY ?hospital ?pro
