REGISTER QUERY GenerateReport AS
PREFIX ex: <http://example.org/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
CONSTRUCT { ?sub1 ?pro1 ?obj1 .
            ?sub2 ?pro2 ?obj2 }
FROM STREAM <http://example.org> [RANGE TRIPLES 4]
FROM <file:///Users/vitor/git-repository/KAFKA/scep-operator/examples/consultation.rdf>
WHERE
{
    ?sub1 ex:hasProfit ?obj1 .
    ?sub2 ex:visited ?obj2 
    BIND (ex:hasProfit AS ?pro1)
    BIND (ex:visited AS ?pro2)
}
