REGISTER STREAM SAttendingDoctorsNFA AS
PREFIX ex: <http://example.org/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX onto: <file:///Users/vitor/git-repository/KAFKA/scep-operator/examples/>
PREFIX dc: <http://purl.org/dc/terms/>
PREFIX dbc: <http://dbpedia.org/page/Category:>
PREFIX dbo: <http://dbpedia.org/ontology/>
PREFIX sioc: <http://rdfs.org/sioc/ns#>
PREFIX schema: <http://schema.org/>
PREFIX nee: <http://www.ics.forth.gr/isl/oae/core#>
SELECT  ?llama ?name ?entity
FROM STREAM <http://example.org> [RANGE TRIPLES 150]
WHERE
{
    SERVICE <http://dbpedia.org/sparql> {?llama rdf:type dbo:Mammal }   
    ?entity nee:hasMatchedURI ?llama .
    ?entity nee:detectedAs ?name    
}